services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: citycare-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/CityCare
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your_strong_secret
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongo

  frontend:
    build: ./frontend/CityCare
    container_name: citycare-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
